config:
  general:
    train_mode: false
    task: instance_segmentation
    seed: null
    checkpoint: checkpoints/horse_mask.ckpt
    backbone_checkpoint: null
    freeze_backbone: false
    linear_probing_backbone: false
    train_on_segments: false
    eval_on_segments: false
    filter_out_instances: false
    save_visualizations: true
    visualization_point_size: 20
    decoder_id: -1
    export: false
    use_dbscan: false
    ignore_class_threshold: 100
    project_name: mask3d_horse_seg
    workspace: jonasschult
    experiment_name: Mask3D_horse_base_eval
    num_targets: 3
    add_instance: true
    dbscan_eps: 0.95
    dbscan_min_points: 1
    add_clip: false
    export_threshold: 0.0001
    reps_per_epoch: 1
    on_crops: false
    body_part_segmentation: false
    scores_threshold: 0.0
    iou_threshold: 1.0
    area: 5
    eval_inner_core: -1
    topk_per_image: -1
    ignore_mask_idx: []
    max_batch_size: 99999999
    save_dir: saved/Mask3D_horse_base_eval
    gpus: 1
    evaluate: false
  data:
    train_mode: train
    validation_mode: validation
    test_mode: validation
    part2human: true
    ignore_label: 255
    add_raw_coordinates: true
    add_colors: true
    add_normals: false
    in_channels: 3
    num_labels: 2
    add_instance: true
    task: instance_segmentation
    add_clip: false
    pin_memory: false
    num_workers: 10
    batch_size: 4
    test_batch_size: 1
    cache_data: false
    voxel_size: 0.02
    reps_per_epoch: 1
    is_mirroring: true
    broken_mirror_version: false
    cropping: false
    cropping_args:
      min_points: 30000
      aspect: 0.8
      min_crop: 0.5
      max_crop: 1.0
    crop_min_size: 20000
    crop_length: 6.0
    cropping_v1: true
    train_dataloader:
      _target_: torch.utils.data.DataLoader
      shuffle: true
      pin_memory: false
      num_workers: 10
      batch_size: 4
    validation_dataloader:
      _target_: torch.utils.data.DataLoader
      shuffle: false
      pin_memory: false
      num_workers: 10
      batch_size: 1
    test_dataloader:
      _target_: torch.utils.data.DataLoader
      shuffle: false
      pin_memory: false
      num_workers: 10
      batch_size: 1
    train_dataset:
      _target_: datasets.semseg.SemanticSegmentationDataset
      dataset_name: human_segmentation
      data_dir:
      - /ssd-disk/data_ssd/pcd_data
      image_augmentations_path: conf/augmentation/albumentations_aug.yaml
      volume_augmentations_path: conf/augmentation/volumentations_aug.yaml
      label_db_filepath: /ssd-disk/data_ssd/pcd_data/part_database.yaml
      color_mean_std: data/processed/synthetic_humans/color_mean_std.yaml
      data_percent: 1.0
      mode: train
      ignore_label: 255
      num_labels: 2
      add_raw_coordinates: true
      add_colors: true
      add_normals: false
      add_instance: true
      cache_data: false
      instance_oversampling: 0.0
      place_around_existing: false
      point_per_cut: 0
      max_cut_region: 0
      flip_in_center: false
      noise_rate: 0
      resample_points: 0
      cropping: false
      cropping_args:
        min_points: 30000
        aspect: 0.8
        min_crop: 0.5
        max_crop: 1.0
      is_tta: false
      crop_min_size: 20000
      crop_length: 6.0
      cropping_v1: true
      area: 5
      reps_per_epoch: 1
      eval_inner_core: -1
      filter_out_classes:
      - 0
      label_offset: 1
      is_elastic_distortion: true
      color_drop: 0.0
      part2human: true
      is_mirroring: true
      broken_mirror_version: false
    validation_dataset:
      _target_: datasets.semseg.SemanticSegmentationDataset
      dataset_name: human_segmentation
      data_dir:
      - /ssd-disk/data_ssd/pcd_data
      image_augmentations_path: null
      volume_augmentations_path: null
      label_db_filepath: /ssd-disk/data_ssd/pcd_data/part_database.yaml
      color_mean_std: data/processed/egobody/color_mean_std.yaml
      data_percent: 1.0
      mode: validation
      ignore_label: 255
      num_labels: 2
      add_raw_coordinates: true
      add_colors: true
      add_normals: false
      add_instance: true
      cache_data: false
      cropping: false
      is_tta: false
      crop_min_size: 20000
      crop_length: 6.0
      cropping_v1: true
      area: 5
      on_crops: false
      eval_inner_core: -1
      filter_out_classes:
      - 0
      label_offset: 1
      part2human: true
    test_dataset:
      _target_: datasets.semseg.SemanticSegmentationDataset
      dataset_name: human_segmentation
      data_dir:
      - ./data/horse/processed
      image_augmentations_path: null
      volume_augmentations_path: null
      label_db_filepath: /ssd-disk/data_ssd/pcd_data/part_database.yaml
      color_mean_std: data/processed/egobody/color_mean_std.yaml
      data_percent: 1.0
      mode: validation
      ignore_label: 255
      num_labels: 2
      add_raw_coordinates: true
      add_colors: true
      add_normals: false
      add_instance: true
      cache_data: false
      cropping: false
      is_tta: false
      crop_min_size: 20000
      crop_length: 6.0
      cropping_v1: true
      area: 5
      on_crops: false
      eval_inner_core: -1
      filter_out_classes:
      - 0
      label_offset: 1
      part2human: true
    train_collation:
      _target_: datasets.utils.VoxelizeCollate
      ignore_label: 255
      voxel_size: 0.02
      mode: train
      small_crops: false
      very_small_crops: false
      batch_instance: false
      probing: false
      task: instance_segmentation
      ignore_class_threshold: 100
      filter_out_classes:
      - 0
      label_offset: 1
      num_queries: 0
    validation_collation:
      _target_: datasets.utils.VoxelizeCollate
      ignore_label: 255
      voxel_size: 0.02
      mode: validation
      batch_instance: false
      probing: false
      task: instance_segmentation
      ignore_class_threshold: 100
      filter_out_classes:
      - 0
      label_offset: 1
      num_queries: 0
    test_collation:
      _target_: datasets.utils.VoxelizeCollate
      ignore_label: 255
      voxel_size: 0.02
      mode: validation
      batch_instance: false
      probing: false
      task: instance_segmentation
      ignore_class_threshold: 100
      filter_out_classes:
      - 0
      label_offset: 1
      num_queries: 0
  logging:
  - _target_: pytorch_lightning.loggers.WandbLogger
    project: mask3d_horse_seg
    name: Mask3D_horse_base_eval
    save_dir: saved/Mask3D_horse_base_eval
    entity: dennis-perrett-mpi-is
    resume: allow
    id: Mask3D_horse_base_eval
  model:
    _target_: models.Mask3D
    hidden_dim: 128
    dim_feedforward: 1024
    num_queries: 1
    num_heads: 8
    num_decoders: 3
    dropout: 0.0
    pre_norm: false
    use_level_embed: false
    normalize_pos_enc: true
    positional_encoding_type: fourier
    gauss_scale: 1.0
    hlevels:
    - 0
    - 1
    - 2
    - 3
    non_parametric_queries: false
    random_query_both: false
    random_normal: false
    random_queries: false
    use_np_features: false
    query_init: None
    clip_proj_dropout: 0.0
    sample_sizes:
    - 200
    - 800
    - 3200
    - 12800
    - 51200
    max_sample_size: false
    shared_decoder: true
    num_classes: 2
    train_on_segments: false
    scatter_type: mean
    voxel_size: 0.02
    config:
      backbone:
        _target_: models.Res16UNet18B
        config:
          dialations:
          - 1
          - 1
          - 1
          - 1
          conv1_kernel_size: 5
          bn_momentum: 0.02
        in_channels: 3
        out_channels: 2
        out_fpn: true
  metrics:
    _target_: models.metrics.ConfusionMatrix
    num_classes: 2
    ignore_label: 255
  optimizer:
    _target_: torch.optim.AdamW
    lr: 0.0001
  scheduler:
    scheduler:
      _target_: torch.optim.lr_scheduler.OneCycleLR
      max_lr: 0.0001
      epochs: 36
      steps_per_epoch: -1
    pytorch_lightning_params:
      interval: step
  trainer:
    deterministic: false
    max_epochs: 36
    min_epochs: 1
    resume_from_checkpoint: null
    check_val_every_n_epoch: 1
    num_sanity_val_steps: -1
  callbacks:
  - _target_: pytorch_lightning.callbacks.ModelCheckpoint
    monitor: train_loss_mask_0
    save_last: true
    save_top_k: 1
    mode: max
    dirpath: saved/Mask3D_horse_base_eval
    filename: '{epoch}-{val_AP_50_parts:.3f}'
    every_n_epochs: 1
  - _target_: pytorch_lightning.callbacks.LearningRateMonitor
  matcher:
    _target_: models.matcher.HungarianMatcher
    cost_class: 2.0
    cost_mask: 5.0
    cost_dice: 2.0
    num_points: -1
  loss:
    _target_: models.criterion.SetCriterion
    num_classes: 2
    eos_coef: 0.1
    losses:
    - labels
    - masks
    num_points: -1
    oversample_ratio: 3.0
    importance_sample_ratio: 0.75
    class_weights: -1
